version: "3.7"

services:
  django:
    container_name: django_rest
    env_file:
      - .env
    build:
      context: ./www
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: ./www
        target: /code
        volume:
          nocopy: true
      - type: bind
        source: ./static
        target: /opt/app/static
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql_django_rest
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  www:
  db_data: {}