# Generated by Django 3.1 on 2020-08-21 03:01

from django.db import migrations, models
import django.db.models.deletion
import drugstore.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(validators=[drugstore.validators.validate_rut])),
                ('dose', models.DecimalField(decimal_places=2, max_digits=2, validators=[drugstore.validators.validate_dose])),
                ('date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.drug')),
            ],
        ),
    ]
