# Generated by Django 3.1 on 2020-08-23 01:01

from django.db import migrations, models
import drugstore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='dose',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[drugstore.validators.validate_dose]),
        ),
    ]
