# Generated by Django 3.1 on 2020-08-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0002_auto_20200822_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drugstore.drug'),
        ),
    ]
